# Supported funding model platforms for The Factor project

# GitHub Sponsors
github: [firmansyah-github]

# Patreon
# patreon: 

# Open Collective
# open_collective: 

# Ko-fi
# ko_fi: 

# Polar
# polar: firmansyah-github

# Buy Me a Coffee
# buy_me_a_coffee: 

# Custom sponsorship URLs (up to 4 custom URLs)
custom: ['https://paypal.me/factorlicense']

